"""Initial schema

Revision ID: 86cf2171e007
Revises: 
Create Date: 2026-05-31 14:32:29.998992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86cf2171e007'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('action_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_categories', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('sensitivity', sa.String(), nullable=True),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('policies_evaluated', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('violations', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('user_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('event_hash', sa.String(), nullable=False),
    sa.Column('previous_hash', sa.String(), nullable=True),
    sa.Column('signature', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_audit_events_agent_id'), 'audit_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_events_time'), 'audit_events', ['time'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('compliance_frameworks', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenants')
    op.drop_index(op.f('ix_audit_events_time'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_agent_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
